### ISSUE TITLE
MacOS support//window controls on the right and offset.

### ISSUE THREAD

**Issue by djenttleman** [nuclearcodecat/shimmer#3] opened 2024-11-08 16:26 UTC
Currently I think this does'nt have OSX support. Window controls are on the right and **offset** as shown in the picture

<img width="140" alt="image" src="https://github.com/user-attachments/assets/e8da6a6c-37f6-4a3c-81ec-468cd030a07b">

-
<img width="685" alt="image" src="https://github.com/user-attachments/assets/f15d8d0f-0e94-4a16-8c38-fd7eb87358f6">

Any ideas?

**Comment by djenttleman** [comment] 2024-11-08 16:28
I think is in the section

/* FOR FIREFOX RELEASE */
#main-window[titlepreface=""] #navigator-toolbox {
  display: flex !important;
  flex-direction: column !important;
}
#main-window[titlepreface="​"] #navigator-toolbox {
  display: flex !important;
  flex-direction: row !important;
}
#main-window[titlepreface="​"] #nav-bar {
  order: 1 !important;
  flex: 1 !important;
}
#main-window[titlepreface="​"] #titlebar {
  order: 2 !important;
}

But I don't know how to change it.

**Comment by nuclearcodecat** [comment] 2024-11-08 17:03
i unfortunately don't have a macos machine to test on TwT
if you could, please send me code / a screenshot from the browser toolbox, targetting ".titlebar-buttonbox". that's the element that contains the buttons. one fix i can think of is the code below. please add it to `userChrome.css` and let me know how it goes.
```.titlebar-buttonbox-container {
  flex: 1 !important;
  justify-content: space-evenly !important;
  align-items: center !important;
} ```

**Comment by djenttleman** [comment] 2024-11-08 19:15
> i unfortunately don't have a macos machine to test on TwT if you could, please send me code / a screenshot from the browser toolbox, targetting ".titlebar-buttonbox". that's the element that contains the buttons. one fix i can think of is the code below. please add it to `userChrome.css` and let me know how it goes.
> 
> ```
> .titlebar-buttonbox-container {
>   flex: 1 !important;
>   justify-content: space-evenly !important;
>   align-items: center !important;
> }
> ```

I've deleted this in userChrome.css: 
`/* FOR FIREFOX RELEASE */
#main-window[titlepreface=""] #navigator-toolbox {
  display: flex !important;
  flex-direction: column !important;`

Then this happened.

<img width="286" alt="image" src="https://github.com/user-attachments/assets/ab981658-bc8d-4432-b695-e7204250c771">

Maybe that is the setting?

**Comment by nuclearcodecat** [comment] 2024-11-08 20:24
i changed this code in the newest version because of a bug. please update and add the code snippet i replied with earlier. let me know how it goes

**Comment by djenttleman** [comment] 2024-11-10 01:27
> i changed this code in the newest version because of a bug. please update and add the code snippet i replied with earlier. let me know how it goes

thanks for the new code
Tried now on macos and this happened.

Fresh install of firefox, almost no extensions and just installed the CSS

Any ideas?

<img width="185" alt="image" src="https://github.com/user-attachments/assets/27ca68bf-fc05-4326-a3e1-f5a55725e6bf">

**Comment by nuclearcodecat** [comment] 2024-11-10 10:45
please add
```
.titlebar-buttonbox {
  align-items: center !important;
}
```
i think this should finally fix it

**Comment by djenttleman** [comment] 2024-11-10 13:05
> please add the code below to `userChrome.css`
> 
> ```
> .titlebar-buttonbox {
>   align-items: center !important;
> }
> ```
> 
> i think this should finally fix it

I'm sorry, this happened

<img width="293" alt="image" src="https://github.com/user-attachments/assets/35ddc3d7-be17-42f2-a065-2e6cbfd61de0">

Removed all flexible spaces and reolad button, removed bookmarks, everything. Not fixed yet.
Tried learning about CSS and modifying it, but nothing either.

**Comment by djenttleman** [comment] 2024-11-10 13:08
FINALLY
Modified the value:

`.titlebar-buttonbox {
  height: 100% !important;
}
`
From 100% to 10%

Then:
<img width="305" alt="image" src="https://github.com/user-attachments/assets/7da0bdfc-52c2-4b76-9ed2-8d2bbbc9ca7a">

This with your code added!!

**Comment by nuclearcodecat** [comment] 2024-11-10 15:17
it can't be 10% because the windows buttons need to be full-height.
i've made this snippet. it's hard to figure stuff out when i don't have a mac lol. please tell me if now it's correct. if not, you could try replacing the `height: 100% !important;` in `.titlebar-button` with `margin: auto auto !important;`

```
/*TODO possible fix for macos icons not centered (#3) */
.titlebar-buttonbox-container {
  justify-content: space-evenly !important;
  align-items: center !important;
}
.titlebar-buttonbox {
  height: 100% !important;
  align-items: center !important;
}
.titlebar-button {
  height: 100% !important;
}
```

**Comment by RyanLiu6** [comment] 2024-11-13 20:44
Hi!

I'm having a slightly similar issue, where the controls are on the right side and are offset, as indicated by the attached image.

![image](https://github.com/user-attachments/assets/e51e9937-b906-4180-bd46-070004d8b6f1)

I've added the most recent snippet to the bottom of `userChrome.css` and restarted via`about:profiles - Restart Normally`. Unfortunately, the issue still resides, not sure if I've done something wrong? 

I'd be happy to go back and forth and try things out. Thanks so much!

**Comment by nuclearcodecat** [comment] 2024-11-14 21:25
@RyanLiu6, could you please enable the browser toolbox (https://firefox-source-docs.mozilla.org/devtools-user/browser_toolbox/index.html), search for `.titlebar-buttonbox-container` in "Search HTML", then right click on this element, click expand all, and send a screenshot of everything contained inside this element? i'd also appreciate if you hovered over one of the `toolbarbutton` elements inside this container (if such exist on macos) and send a screenshot of the highlighted item (you will have to take a screenshot of the browser window while hovering in the browser toolbox, so split your screen between these two)

**Comment by RyanLiu6** [comment] 2024-11-15 00:37
@nuclearcodecat Thanks for the quick response! Below I've attached the requested screenshots. Let me know if I didn't capture exactly what I was supposed to btw! 

This is `.titlebar-buttonbox-container`:
![Screenshot 2024-11-14 at 4 26 00 PM](https://github.com/user-attachments/assets/7e3735c3-feec-466f-98cb-60fc22190660)

This is hovering over the `hbox` element with `.titlebar-buttonbox-container` class:
![Screenshot 2024-11-14 at 4 30 39 PM](https://github.com/user-attachments/assets/54ed2e5a-9819-441b-b239-bfabf958cb4a)

This is hovering over the `hbox` element with `titlebar-buttonbox` class:
![Screenshot 2024-11-14 at 4 30 45 PM](https://github.com/user-attachments/assets/062cef8e-c39d-49e1-bb92-ede8465ec4af)

This is hovering over the `toolbarbutton` element:
![Screenshot 2024-11-14 at 4 30 53 PM](https://github.com/user-attachments/assets/f3914870-a636-4bc0-821c-ea374c37acee)

Upon further inspection, I noticed that these were `display: none`:
![image](https://github.com/user-attachments/assets/b06d71ff-fcd6-4d85-8f85-794776e371f9)

Not sure if that's intended, but changing it to flex did result in something being highlighted upon hovering:
![image](https://github.com/user-attachments/assets/2103b7d9-48a6-4ab2-a73e-fc49ab1b913a)

(Although this did end up being the Red X button instead of the Yellow minimize button in the middle)

**Comment by nuclearcodecat** [comment] 2024-11-16 16:48
it looks like the macos buttons might be implemented in some other way than on windows. in the top-left of the browser toolbox, there is a button which allows you to select an element. try selecting one of the buttons with this tool

**Comment by RyanLiu6** [comment] 2024-11-18 06:08
> it looks like the macos buttons might be implemented in some other way than on windows. in the top-left of the browser toolbox, there is a button which allows you to select an element. try selecting one of the buttons with this tool. sorry for the long wait

Hi! I've created #21 to hopefully fix this issue. I inspected the elements a bit more over the weekend and think the issue is because MacOS has stricter controls over the behaviour and style of the three control buttons, thus leading to the weird appearance I ran into. I go into further details (honestly not much lol) in the PR but thank you for pointing me into the right direction :). Theme is great and I'd be happy to help and contribute on fixing other MacOS related issues! Cheers!

**Comment by kirloi** [comment] 2024-11-21 23:30
Hello guys just pitching in since i was made aware im not the only one having this trouble. I tested it on my M2, but i have so much mangled code and mix match of chromes I can't be certain it will work. Im just a Designer that oftens works with CSS so take my findings with a grain of salt.

Try the following:

```
/*TODO possible fix for macos icons not centered (#3) */
.titlebar-buttonbox-container {
  justify-content: space-evenly !important;
  align-items: start !important;
  /* height: 2.5rem !important; */ [This should be removed or commented or your styles]
}
.titlebar-buttonbox {
  height: 100% !important;
  align-items: start !important;
  margin-top: -1rem;
}
.titlebar-button {
  height: 100% !important;
}
```

**Comment by loaxley** [comment] 2024-11-29 09:13
Hello all. I am having a similar issue that pertains to MacOS support. However, instead of the window control being on the wrong side and improperly offset/aligned...I don't see the window controls at all.

I tested this on a clean build of Firefox with no addons other than Sidebery. Everything was done per the instructions. Whether Sidebery sidebar is shown or not, there are no window controls at all.

Any suggestions?

<img width="1270" alt="Screenshot 2024-11-29 at 1 10 56 AM" src="https://github.com/user-attachments/assets/dd1a5bad-e809-4b89-bedf-c0329851f9a5">

<img width="1282" alt="Screenshot 2024-11-29 at 1 10 44 AM" src="https://github.com/user-attachments/assets/a2bc3428-9372-4d08-9fa8-714d4853f18a">

**Comment by nuclearcodecat** [comment] 2024-11-29 09:20
@loaxley yeah open a new issue. i don't know why this would happen, i unfortunately can't debug on macos, so i can't really help. it's probably something about the container being of a tiny width OR it's something with the recent menubar support. try removing the styles under the `=== menubar ===` comment

**Comment by loaxley** [comment] 2024-11-30 00:14
> @loaxley yeah open a new issue. i don't know why this would happen, i unfortunately can't debug on macos, so it's hard to help. it's probably something about the container being of a tiny width OR it's something with the recent menubar support. try removing the styles under the `=== menubar ===` comment

I can confirm that commenting out this snippet makes the window control re-appear on MacOS

#toolbar-menubar:not([inactive]) ~ #TabsToolbar .titlebar-buttonbox-container {
  display: none !important;
}

**Comment by cwttdb70** [comment] 2024-11-30 01:08
Hi, another mac user here! Picking up where the last person left off....here's what has fixed it for me - 3 simple changes to UserChrome.css you can see here

https://github.com/nuclearcodecat/shimmer/compare/main...cwttdb70:shimmer:main

It is my opinion though you may disagree that window controls should ALWAYS be on the left side on Mac.

**Comment by cwttdb70** [comment] 2024-11-30 23:42
Some more context from Reddit:

https://www.reddit.com/r/FirefoxCSS/comments/1h2ryml/it_seems_133_broke_a_lot_of_themes/

_#titlebar doesn't exist anymore.

 Before 133 the tree was like:

#navigator-toolbox > #titlebar > #toolbar-menubar / #TabsToolbar

But now #titlebar is just gone so #toolbar-menubar and #TabsToolbar are both directly children of #navigator-toolbox along with #nav-bar and #PersonalToolbar

Both of them gained the class .browser-titlebar ... the window controls are children of #TabsToolbar_

**Comment by nuclearcodecat** [comment] 2024-12-06 22:20
i pushed cwttdb70's pr, closing

**Closed by nuclearcodecat** 2024-12-06 22:20 UTC
